### PR TITLE
Add gitignore for QT programming language

### PR DESCRIPTION
**Pull request by imjoey**
Previously there was no `gitignore` file, so add it into repo which is copied from https://github.com/github/gitignore/blob/master/Qt.gitignore .

### CODE REVIEW

**Comment by handsome-feng** [comment]
Hi, joey, we don't use .gitignore because we must keep the project directory clean and dput it to Debian/Ubuntu archive, but this file hide build files when 'git status' ,  although we can use 'git status --ignore', but it's not convenient.

**Comment by imjoey** [comment]
@handsome-feng  Hi, thanks for your in-depth explanation. I'll close this pr. BTW, how about the `.travis.yml` for Travis CI integration? As for it's been merged and shall we need to remove it? Thanks.

**Comment by handsome-feng** [comment]
The .travis.yml is fine to keep there, and thanks for getting it done. :)

**Comment by imjoey** [comment]
> The .travis.yml is fine to keep there, and thanks for getting it done. :)

 @handsome-feng thanks for your feeback. If it's all right, I would add Travis-CI integration for more projects. 😄

**Pull request closed without merging**
